### ISSUE TITLE
Installation warning using composer

### ISSUE THREAD

**Issue by hew86i** [bagisto/bagisto-bulk-upload#13]
**Deprecation Notice**:  Class [Classname] located in [path]does not psr-4 autoloading standard. It will not autoload anymore in Composer v2.0.
Please fix this
I am using Bagisto v.1.2.0

**Comment by vaishaliwebkul** [comment]
@hew86i 
please mention your composer version

**Comment by hew86i** [comment]
composer v1.10.7

**Comment by hew86i** [comment]
Hi,

maybe in installation step 2 this:
`"Webkul\\Bulkupload\\": "packages/Webkul/Bulkupload"`
needs to be 
`"Webkul\\Bulkupload\\": "packages/Webkul/Bulkupload/src"`   

?

**Comment by prateek-webkul** [comment]
@hew86i ,

Fixed warning issue..
