### ISSUE TITLE
composer require bagisto/bulk-upload not working

### ISSUE THREAD

**Issue by palmatesolutions** [bagisto/bagisto-bulk-upload#31]
[InvalidArgumentException]
  Could not find a matching version of package bagisto/bulk-upload. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-
  stability (dev).

**Comment by prateek-webkul** [comment]
Hello @palmatesolutions ,

could you mention your bagisto version( go to the .env and check app_version)

Thanks

**Comment by palmatesolutions** [comment]
APP_VERSION=1.2.0-BETA1

**Comment by prateek-webkul** [comment]
@palmatesolutions ,

We are checking for the issue, you may now try setuping without composer command..

**Comment by shlewa** [comment]
I have the same issue, I also tried installing without using composer but instead doing this:
Unzip the respective extension zip and then merge "packages" and "storage" folders into project root directory.
Goto config/app.php file and add following line under 'providers'
Webkul\Bulkupload\Providers\BulkUploadServiceProvider::class
Goto composer.json file and add following line under 'psr-4'
"Webkul\\Bulkupload\\": "packages/Webkul/Bulkupload/src"
Goto config/concord.php file and add following line under 'modules'
\Webkul\Bulkupload\Providers\ModuleServiceProvider::class
Run these commands below to complete the setup
composer dump-autoload
php artisan migrate
php artisan storage:link
php artisan route:cache
php artisan vendor:publish

-> Press 0 and then press enter to publish all assets and configurations.

STILL NOT WORKING

**Comment by shlewa** [comment]
found the solution, do this to install instead:
php artisan clear-compiled 
composer dump-autoload
php artisan optimize
php artisan migrate
php artisan storage:link
php artisan route:cache
php artisan vendor:publish

this works.

**Comment by prateek-webkul** [comment]
@palmatesolutions @shlewa ,

We have register the package, please use the below command to setup the module... 

**composer require bagisto/bagisto-bulk-upload**

Thanks

**Comment by prateek-webkul** [comment]
@palmatesolutions @shlewa ,

We are closing the issue, if still issue exists feel free to open.

Thanks
