### ISSUE TITLE
Route error on v1.3

### ISSUE THREAD

**Issue by jovicacosmic** [bagisto/bagisto-bulk-upload#45]
When visiting /admin/dataflowprofile

The DELETE method is not supported for this route. Supported methods: GET, HEAD, POST. (View: /home/user/projects/valet/bagisto/vendor/bagisto/bagisto-bulk-upload/src/Resources/views/admin/bulk-upload/data-flow-profile/index.blade.php)

![image](https://user-images.githubusercontent.com/78356988/108347938-7174ea80-71e1-11eb-8323-25f1888f52ed.png)

**Comment by prateek-webkul** [comment]
Hello @jovicacosmic ,

We are in progress for compatibility of this module, but you may fix this error by replacing the Admin/ProfileDataGrid.php file prepareMassActions method DELETE to POST.
