### ISSUE TITLE
Best wat to relocate the module in order to have it under git version control

### ISSUE THREAD

**Issue by juancantor12** [bagisto/bagisto-bulk-upload#46]
Hi, i ran into a particular problem where i have to do some changes to the add-on in order to meet a client requirements, i've had to modify some files under /vendor/bagisto/bagisto-bulk-upload/ and under /storage/, folders who are both under .gitignore.
I'm in the need now to make some large changes, mostly due to language of the sample templates and some custom behaviour in the upload process, i have read some options to move a package out of vendor an load it via psr-4 in composer, i was looking at the read.me of this addon and the way to instal it without composer is merging "packages" and "storage" folders and signin in the module in config/app.php and config/concord.php, however i'm not sure what or where the "package" folder of the module is, so i can move it out of vendor and have it versioned, thanks and sorry if this is not the place to ask for, i'm kind of stuck here.

**Comment by prateek-webkul** [comment]
Hey @juancantor12 ,
 
Do you want to run this module from the packages/Webkul folder of your bagisto project, then you may refer the directory structure from the link (https://github.com/prateek-webkul/bagisto-bulk-upload/tree/v1.2.0), as it is an old branch so many of issue may be there, you may only follow the directory structure.

Or, you can easily go up with the latest version under vendor/bagisto directory of project.

If still you have an query, feel free write to us.

Thanks

**Comment by juancantor12** [comment]
Since i originally installed it via composer, i have the vendor/bagisto structure, so i guess the instructions (From this version) to merge the "packages" and "storage" folder instruction is no longer valid, ¿Is there any way to move mi composer-installed lastest version from vendor/bagisto to /packages/webkul to run it from there and keep git version control over it?

**Comment by prateek-webkul** [comment]
If you want to use the package in the package/Webkul then you may create the exact directory structure as specified in above link  with the latest code. Also, can you specify is there any issue to use the package from the vendor directory ?

**Comment by juancantor12** [comment]
The issue is that i'm makig some changes on the package due to client language requirements (on templates) and some custom behaviour so i need to keep those changes under git control, but i'm not versioning all the vendor and i need my changes to be out of composer control, i will try to relocate it the way you said and will let you know how that works, thanks for your time, i really appreciate it.

**Comment by juancantor12** [comment]
Hi, sorry for the delay, i followed the instructions of the link that you provided with the lastest code at the moment and it seems to be working without any problems under /packages/Webkul/Bulkupload, thanks for your help.
