### ISSUE TITLE
How upload pictures together?

### ISSUE THREAD

**Issue by fhferreira** [bagisto/bagisto-bulk-upload#5]
I tried to upload a zip with pictures together with product and into the csv/xlsx column images I added the 'images path' but nothing is happen.

**Comment by fhferreira** [comment]
any help?

**Comment by prateek-webkul** [comment]
@fhferreira ,
instead of image path, please add the image name. And, retry to upload the products...

**Comment by fhferreira** [comment]
> @fhferreira ,
> instead of image path, please add the image name. And, retry to upload the products...

So you mean all images will need to be at ROOT of .zip file?

**Comment by prateek-webkul** [comment]
Yes..
