### ISSUE TITLE
Locale based Product Bulk Upload 

### ISSUE THREAD

**Issue by sharathdn** [bagisto/bagisto-bulk-upload#6]
Currently the bulk product upload supports only one default language, need to support multiple locales.

**Comment by prateek-webkul** [comment]
Hello @sharathdn,

The selected locale in channel are used for bulk upload. The products will be uploaded in locale which is selected in admin->channels.

**Comment by sharathdn** [comment]
Hello Prateek,
Thanks for the reply.
What if I want to upload  products with multiple locales?

**Comment by prateek-webkul** [comment]
Hello @sharathdn ,
For now, the products are getting uploaded to different locales but fields like names are missing. You need to edit product for other attributes.

**Comment by sharathdn** [comment]
Thanks Prateek.

It will be painful for updating huge products one by one.

**Comment by prateek-webkul** [comment]
Yes, maybe we'll implement this feature in future or you may do PR for this issue..

**Comment by sharathdn** [comment]
Thank you for the update.

**Comment by bureauvk** [comment]
Can't we temporarily change the default locale after doing the first import, and then do the second import?

**Comment by prateek-webkul** [comment]
Hello @bureauvk @sharathdn ,

We have fixed the issue. Now, the product will be uploaded to locale which is selected within channel..

**Comment by irisda** [comment]
Hello @prateek-webkul , did you fix the problem of adding the same product in different languages?
