### ISSUE TITLE
Unable to upload xls samples for all the products

### ISSUE THREAD

**Issue by Nikitajoshi39** [bagisto/bagisto-bulk-upload#64]
**Actual result**

When we download the Xls samples we get CSV samples for all the products.

https://user-images.githubusercontent.com/92033944/140927698-18fd645e-e23f-4181-9030-6b0d0a769660.mp4

**Expected result**

Download the Xls samples should get Xls samples for all the products.

**Comment by ghermans** [comment]
@Nikitajoshi39 do you have an update regarding this ?

**Comment by prateek-webkul** [comment]
@ghermans ,

yes, now the issue is fixed.
