### ISSUE TITLE
Error in table with prefix

### ISSUE THREAD

**Issue by Bunix** [bagisto/bagisto-bulk-upload#7]
After Installing Bulk-upload extension the packages cannot detect or collaborate to table with prefix.

**Comment by prateek-webkul** [comment]
Hello @Bunix,
We are checking this issue and will get back ASAP ....

**Comment by Bunix** [comment]
thanks

**Comment by prateek-webkul** [comment]
@Bunix ,

Please provide us the steps to reproduce the issue, and specify your bagisto version...

Thanks

**Comment by prateek-webkul** [comment]
@Bunix,

Hope your query has been resolved, we are closing the issue. If still you have some doubts or issues, feel free to open the issue...

Thanks
