### ISSUE TITLE
multiselect attribute in configurable product upload

### ISSUE THREAD

**Issue by Sharatheywa** [bagisto/bagisto-bulk-upload#8]
Need help in passing multiselect/checkbox type attributes in configurable product upload.

**Comment by prateek-webkul** [comment]
Hello @Sharatheywa,

We don't have support on multiselect/checkbox type attributes in configurable product till now. We will try to implement it..

Thanks for notifying us...

Thanks

**Comment by Sharatheywa** [comment]
Hello @prateek-webkul 
Any Idea when it will be implemented ?

Thanks

**Comment by vaishaliwebkul** [comment]
@Sharatheywa 
Currently, we can't provide the exact time when it implements, but if you want this feature soon then it will be counted as customization.
you may raise the ticket here support@bagisto.com if you want this feature soon.

**Comment by prateek-webkul** [comment]
@Sharatheywa ,

The issue has been fixed now in https://github.com/bagisto/bagisto-bulk-upload/tree/v.1.2.0

Thanks
